builtin setopt \
    ALWAYS_TO_END \
    AUTO_CD \
    AUTO_LIST \
    AUTO_MENU \
    AUTO_PARAM_SLASH \
    AUTO_PUSHD \
    AUTO_RESUME \
    BANG_HIST \
    BEEP \
    COMBINING_CHARS \
    CORRECT \
    EXTENDED_GLOB \
    EXTENDED_HISTORY \
    HIST_BEEP \
    HIST_EXPIRE_DUPS_FIRST \
    HIST_FCNTL_LOCK \
    HIST_IGNORE_DUPS \
    HIST_IGNORE_SPACE \
    HIST_REDUCE_BLANKS \
    HIST_SAVE_NO_DUPS \
    INTERACTIVE_COMMENTS \
    LONG_LIST_JOBS \
    NOTIFY \
    PUSHD_IGNORE_DUPS \
    PUSHD_SILENT \
    RC_QUOTES \
    SHARE_HISTORY

builtin unsetopt \
    CHECK_JOBS \
    FLOW_CONTROL \
    HUP \
    MAIL_WARNING \
    MENU_COMPLETE
